import = [
  "~/.config/alacritty/themes/themes/nordic.toml"
]

live_config_reload = true

[shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "/opt/homebrew/bin/tmux a -t 0 || /opt/homebrew/bin/tmux -u",
]

[window]
dimensions = { columns = 200, lines = 60 }
padding = { x = 8, y = 4 }
opacity = 0.90
title = "Alacritty"
option_as_alt = "Both"

[cursor]
style = "Beam"

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 12
offset = { x = 0, y = 1 }

[env]
TERM = "alacritty-direct"

[keyboard]
bindings = [
  { key = "B", mods = "Command", action = "None" }
]
