"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$memory_usage\
$fill\
$golang\
$package\
$nodejs\
$deno\
$terraform\
$gcloud\
$line_break\
$character\
"""

right_format = """
$cmd_duration\
$time\
"""

[fill]
symbol = " "

[character]
success_symbol = '[╰─>\$](bold cyan)'
error_symbol = '[╰─>\$](bold red)'

[sudo]
disabled = false
symbol = ' 󰿆 sudo'
format = """
[$symbol]($style)\
"""
style = "bold yellow"

[direnv]
disabled = false
format = """
[$symbol$allowed]($style)\
"""
style = "bold green"

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false

[package]
format = '[🎁 $version](bold 208) '

[terraform]
format = '[$symbol$version $workspace]($style)'
symbol = " "
detect_files = ['.terraform-version']

[memory_usage]
disabled = false
threshold = 85
style = 'bold dimmed green'
symbol = "󰍛"
format = ' $symbol [${ram}( | ${swap})]($style) '

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
format = '[┬─\[$path\]]($style)[$read_only]($read_only_style) '
truncation_length = 2
truncate_to_repo = true
read_only = " 󰌾"
fish_style_pwd_dir_length = 1
home_symbol = "~"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "
truncation_length = 8
format = """
[$symbol$branch(:$remote_branch)]($style)\
"""

[git_status]
disabled = false
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '\$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = "([  $all_status$ahead_behind]($style))"

[git_metrics]
disabled = false
only_nonzero_diffs = true
format = "([  +$added]($added_style)[-$deleted]($deleted_style))"

[golang]
symbol = " "
format = ' [$symbol($version )($mod_version )]($style)'

[deno]
format = ' [🦕 $version](green bold)'

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
format = '[$symbol($version)]($style)'
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[time]
disabled = false
format = '[ $time](bold cyan)'
time_format = '%T'

[cmd_duration]
show_milliseconds = false
min_time = 1000
show_notifications = true
format = '[󰞌 $duration ](bold yellow)'

[gcloud]
symbol = "󱇶 "
style = "bold blue"
format = " [$symbol($project)]($style)"
