[tools]
node = "lts"
"npm:@fsouza/prettierd" = "latest"
"npm:@taplo/cli" = "latest"
"npm:@vue/language-server" = "latest"
"npm:@vue/typescript-plugin" = "latest"
"npm:bash-language-server" = "latest"
"npm:css-variables-language-server" = "latest"
"npm:cssmodules-language-server" = "latest"
"npm:cz-conventional-changelog" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:eslint_d" = "latest"
"npm:git-cz" = "latest"
"npm:git-split-diffs" = "latest"
"npm:lehre" = "latest"
"npm:netlify-cli" = "latest"
"npm:ts-node" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:wrangler" = "latest"
"npm:yaml-language-server" = "latest"
"npm:sql-formatter" = "latest"
"npm:sql-formatter-cli" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@aikidosec/safe-chain" = "latest"
"npm:@openai/codex" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:vercel" = "latest"
"npm:@antfu/ni" = "latest"

[settings]
idiomatic_version_file = true
