shell = "zsh"

# デフォルトを遅延読み込みにする
apply = ['defer']

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

# zsh-syntax-highlighting
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

# zsh-autosuggestions
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["source"]

# zsh-history-substring-search
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["source"]

# starship
[plugins.starship]
inline = 'eval "$(starship init zsh)"'

# zsh配下のファイルは遅延読み込みする
[plugins.local-defers]
local = "~/dotfiles/zsh"
use = ["{!sync,*}.zsh"]

# zsh/sync配下のファイルは遅延読み込みしない
[plugins.local-sync]
local = "~/dotfiles/zsh"
use = ["sync/*.zsh"]
apply = ["source"]
