return {
	{ import = "plugins.ai" },
	{ import = "plugins.git" },
	{ import = "plugins.csv" },
	{ import = "plugins.go" },
	{ import = "plugins.color-scheme" },
	{ import = "plugins.fzf" },
	{ import = "plugins.lsp" },
	{ import = "plugins.markdown" },
	{ import = "plugins.obsidian" },
	-- { import = "plugins.telescope" },
	{ import = "plugins.treesitter" },
	{ import = "plugins.typescript" },
	{ import = "plugins.ui" },
	{ import = "plugins.utility" },
}
